export const ErrorCode = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',

  INVALID_TIME_ENTRY: 'INVALID_TIME_ENTRY',
  JOURNEY_ALREADY_FINISHED: 'JOURNEY_ALREADY_FINISHED',
  DUPLICATE_TIME_ENTRY: 'DUPLICATE_TIME_ENTRY',
  TIME_ENTRY_OUT_OF_SEQUENCE: 'TIME_ENTRY_OUT_OF_SEQUENCE',

  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  MANAGER_REQUIRED: 'MANAGER_REQUIRED',
  CANNOT_MANAGE_EMPLOYEE: 'CANNOT_MANAGE_EMPLOYEE',

  TIME_OFF_NOT_FOUND: 'TIME_OFF_NOT_FOUND',
  TIME_OFF_NOT_PENDING: 'TIME_OFF_NOT_PENDING',
  TIME_OFF_REJECTION_REASON_REQUIRED: 'TIME_OFF_REJECTION_REASON_REQUIRED',
  TIME_OFF_ALREADY_EXISTS: 'TIME_OFF_ALREADY_EXISTS',

  VACATION_NOT_FOUND: 'VACATION_NOT_FOUND',
  VACATION_INVALID_RANGE: 'VACATION_INVALID_RANGE',
  VACATION_OVERLAP: 'VACATION_OVERLAP',
  VACATION_INSUFFICIENT_BALANCE: 'VACATION_INSUFFICIENT_BALANCE',
  VACATION_NOT_PENDING: 'VACATION_NOT_PENDING',
  VACATION_REJECTION_REASON_REQUIRED: 'VACATION_REJECTION_REASON_REQUIRED',

  TIME_BANK_INVALID_MINUTES: 'TIME_BANK_INVALID_MINUTES',
  TIME_BANK_NOTE_REQUIRED: 'TIME_BANK_NOTE_REQUIRED',

  SCHEDULE_NOT_FOUND: 'SCHEDULE_NOT_FOUND',
  HOLIDAY_NOT_FOUND: 'HOLIDAY_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
